import { execSync } from 'node:child_process';
import { copyFileSync, cpSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { styleText } from 'node:util';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_PATH = resolve(__dirname, '../../dist/ngx-auth');

const log = str => console.log(styleText('magenta', str));

const runCmd = (cmd, args, verbose = true) => {
    try {
        execSync(`${cmd} ${args.join(' ')}`, { stdio: verbose ? 'inherit' : 'pipe' });
    } catch {
        process.exit(1);
    }
};

const buildSchematics = () => {
    const schematicsPath = resolve(__dirname, 'schematics');

    log('> Building schematics..');
    runCmd('tsc', ['-p', resolve(schematicsPath, 'tsconfig.prod.json')]);

    log('> Copying schematics assets..');
    copyFileSync(resolve(schematicsPath, 'ng-add/schema.json'), resolve(DIST_PATH, 'schematics/ng-add/schema.json'));
    copyFileSync(resolve(schematicsPath, 'collection.json'), resolve(DIST_PATH, 'schematics/collection.json'));
    copyFileSync(resolve(schematicsPath, 'package.json'), resolve(DIST_PATH, 'schematics/package.json'));
};

const buildLib = () => {
    log('> Building library..');
    runCmd('nx', ['run', 'ngx-auth:build-lib']);

    log('> Copying assets..');
    cpSync(resolve(__dirname, '../auth-js/oidc/assets'), resolve(DIST_PATH, 'oidc/assets'), { recursive: true });
    copyFileSync(resolve(__dirname, 'CHANGELOG.md'), resolve(DIST_PATH, 'CHANGELOG.md'));
    copyFileSync(resolve(__dirname, 'README.md'), resolve(DIST_PATH, 'README.md'));
    copyFileSync(resolve(__dirname, '../../LICENSE'), resolve(DIST_PATH, 'LICENSE'));

    /**
     * Angular 14 use a version of Webpack that does not fully support the 'exports' field in package.json.
     * It will find the 'type:module' field and thus try to load the 'module' field from the 'exports' which does not exists.
     * But 'ng-packagr' is already generating sub package.json's for each entry points (only it is for development and not for production).
     * So as a workaround we simply remove the '.npmignore' file and takes advantage of the sub package.json's generated by 'ng-packagr'.
     */
    log('> Removing ng-packagr\'s .npmignore from dist..');
    rmSync(resolve(DIST_PATH, '.npmignore'), { force: true });
};

void (() => {
    try {
        log('> Cleaning..');
        rmSync(DIST_PATH, { recursive: true, force: true });
        buildLib();
        buildSchematics();
        styleText('green', '> Done!\n');
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
})();
