// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]

    docsSidebar: [
        {
            label: 'Introduction',
            type: 'doc',
            id: 'getting-started/intro'
        },
        {
            label: 'Getting started',
            type: 'category',
            collapsed: false,
            items: [
                'getting-started/vanilla-js',
                'getting-started/angular',
                'getting-started/vue-js',
                'getting-started/mobile',
                'getting-started/providers'
            ]
        },
        {
            label: 'Configuration',
            type: 'doc',
            id: 'getting-started/configuration'
        },
        {
            label: 'Usage',
            type: 'doc',
            id: 'getting-started/usage'
        },
        {
            label: 'Playground',
            type: 'doc',
            id: 'getting-started/playground'
        }
    ],

    guidesSidebar: [
        {
            label: 'Guide',
            type: 'doc',
            id: 'guides/guides'
        }
    ],

    apisSidebar: [
        {
            label: 'VanillaJS',
            type: 'category',
            collapsed: false,
            items: [
                'api/vanilla-js/auth-manager'
            ]
        },
        {
            label: 'Angular',
            type: 'category',
            collapsed: false,
            items: [
                'api/angular/auth-service',
                'api/angular/auth-guard',
                'api/angular/auth-interceptor'
            ]
        },
        {
            label: 'Mobile',
            type: 'doc',
            id: 'api/mobile'
        }
    ]
};

export default sidebars;
