name: Deploy demo-app to GitHub Pages

on:
  push:
    branches:
      - main
    tags-ignore:
    - '**'
    paths-ignore:
    - 'projects/site/**'

jobs:
  ci_demo-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: npm
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint:demo-app
      - name: Build demo-app-auth-js
        env:
          baseUrl: /${{ github.event.repository.name }}/demo-app/auth-js/
        run: npm run build:demo-app-auth-js -- --base-href=${{ env.baseUrl }} --deploy-url=${{ env.baseUrl }}
      - name: Build demo-app-ngx-auth
        env:
          baseUrl: /${{ github.event.repository.name }}/demo-app/ngx-auth/
        run: npm run build:demo-app-ngx-auth -- --base-href=${{ env.baseUrl }} --deploy-url=${{ env.baseUrl }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/demo-app
          destination_dir: demo-app
          commit_message: 'deploy(demo-app):'
