name: Deploy demo-app

on:
    push:
        branches:
            - main
        tags-ignore:
            - '**'
        paths-ignore:
            - 'apps/website/**'
    workflow_dispatch:

concurrency:
    group: deploy-demo-app-group-${{ github.ref }}
    cancel-in-progress: true

env:
    NODE: 18
    HUSKY: 0

jobs:
    ci_tests:
        concurrency:
            group: Run tests-${{ github.ref }}
            cancel-in-progress: true
        uses: ./.github/workflows/ci_tests.yml

    ci_demo-app:
        needs: ci_tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE }}
                  registry-url: https://registry.npmjs.org/
                  cache: npm

            - name: Install latest npm
              run: npm install -g npm@latest

            - name: Cache .angular and node_modules
              uses: actions/cache@v4
              id: cache-step
              with:
                  key: cache-ubuntu-latest-node${{ env.NODE }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      cache-ubuntu-latest-node${{ env.NODE }}-
                  path: |
                      .angular/cache
                      node_modules

            - name: Install dependencies
              if: steps.cache-step.outputs.cache-hit != 'true'
              run: npm clean-install --engine-strict

            #   - name: Lint demo-app
            #     working-directory: apps/demo-app
            #     run: npm run lint

            - name: Build demo-app:auth-js
              working-directory: apps/demo-app/web
              env:
                  baseUrl: /${{ github.event.repository.name }}/demo-app/auth-js/
              run: npm run build:auth-js -- --base-href=${{ env.baseUrl }} --deploy-url=${{ env.baseUrl }}

            - name: Build demo-app:ngx-auth
              working-directory: apps/demo-app/web
              env:
                  baseUrl: /${{ github.event.repository.name }}/demo-app/ngx-auth/
              run: npm run build:ngx-auth -- --base-href=${{ env.baseUrl }} --deploy-url=${{ env.baseUrl }}

            - name: Build demo-app:auth-vue
              working-directory: apps/demo-app/web
              env:
                  baseUrl: /${{ github.event.repository.name }}/demo-app/auth-vue/
              run: npm run build:auth-vue -- --base-href=${{ env.baseUrl }} --deploy-url=${{ env.baseUrl }}

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/demo-app
                  destination_dir: demo-app
                  commit_message: 'deploy(demo-app):'
