name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci_site.yml'
      - 'projects/site/**'
    tags-ignore:
      - '**'

jobs:
  ci_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: npm
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Build site
        working-directory: projects/site
        run: |
          npm clean-install
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/site/build
          destination_dir: site
          commit_message: 'deploy(site):'
