name: CI tests

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - 'projects/site/**'
  pull_request:
  workflow_dispatch:

jobs:
  ci_tests:
    name: Tests on linux node${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
