name: Test auth-js

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_auth-js]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_auth-js.yml'
            - 'libs/auth-js/**'

env:
    HUSKY: 0

concurrency:
    group: ci-test-auth-js-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_auth-js:
        uses: badisi/actions/.github/workflows/action.yml@v2
        with:
            working-directory: libs/auth-js
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[22]'
            lint: true
            test: true

    ci_test_deps:
        needs: ci_test_auth-js
        runs-on: 'ubuntu-latest'
        steps:
            - name: Test ngx-auth
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_ngx-auth

            - name: Test auth-vue
              uses: peter-evans/repository-dispatch@v3
              with:
                  event-type: test_auth-vue
