name: Run tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'projects/site/**'
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_tests:
    name: Tests on ${{ matrix.os }} node${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: npm

      # https://github.com/actions/setup-node/issues/411
      # https://github.com/npm/cli/issues/4341
      - name: Workaround for npm installation on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm install -g npm@8.3.1

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Cache .angular and node_modules
        uses: actions/cache@v3
        id: cache-step
        with:
          key: cache-${{ matrix.os }}-node${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-${{ matrix.os }}-node${{ matrix.node }}-
          path: |
            .angular/cache
            node_modules

      - name: Install dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: npm clean-install --engine-strict

      - name: Lint libs
        run: npm run lint:libs

      - name: Test libs
        run: npm run test:libs

      - name: Build auth-js
        working-directory: projects/auth-js
        run: npm run build

      - name: Build ngx-auth
        working-directory: projects/ngx-auth
        run: npm run build
