name: Test auth-vue

on:
    workflow_dispatch:
    repository_dispatch:
        types: [test_auth-vue]
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
        paths:
            - '.github/workflows/ci_test_auth-vue.yml'
            - 'libs/auth-vue/**'

env:
    HUSKY: 0

concurrency:
    group: ci-test-auth-vue-group-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci_test_auth-vue:
        uses: badisi/actions/.github/workflows/action.yml@v2
        with:
            working-directory: libs/auth-vue
            runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
            node-versions: '[22]'
            lint: true
            test: true
